# Generated by Django 4.0.4 on 2022-07-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('España', 'España'), ('Italia', 'Italia'), ('Alemania', 'Alemania'), ('Francia', 'Francia'), ('Inglaterra', 'Inglaterra')], max_length=10)),
                ('year', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)])),
                ('matchday', models.IntegerField()),
                ('local_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
            ],
        ),
    ]
