# Generated by Django 4.0.4 on 2022-07-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0002_alter_match_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.CharField(choices=[('ESP', 'España'), ('IT', 'Italia'), ('GER', 'Alemania'), ('FR', 'Francia'), ('ENG', 'Inglaterra')], max_length=10),
        ),
    ]
