# Generated by Django 4.0.4 on 2022-07-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0003_alter_match_league'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='year',
            new_name='año',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='local_team',
            new_name='equipo_local',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='away_team',
            new_name='equipo_visitante',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='matchday',
            new_name='jornada',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='league',
            new_name='liga',
        ),
    ]
