# Generated by Django 4.0.4 on 2022-07-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0004_rename_year_match_año_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='año',
            field=models.IntegerField(),
        ),
    ]
